### ISSUE TITLE
Website link returns 404

### ISSUE THREAD

**Issue by sunjam** [sbrl/Pepperminty-Wiki#212] opened 2020-09-19 20:49 UTC
https://starbeamrainbowlabs.com/peppermint/

**Comment by sbrl** [comment] 2020-09-21 16:26
Heya! That's really odd. Where do you see that link? I can't find anywhere that mentions that. It should be either 1 of these 2:

 - https://starbeamrainbowlabs.com/labs/peppermint/__nightdocs/01-Welcome.html
 - https://peppermint.mooncarrot.space/

**Comment by sunjam** [comment] 2020-09-21 17:33
https://starbeamrainbowlabs.com/labs/peppermint/build/index.php?page=Main%20Page

I believe this one

**Comment by sbrl** [comment] 2020-09-22 17:25
Hrm, that's really strange. I see a link to the downloader there, which sends me to <https://starbeamrainbowlabs.com/labs/peppermint/download.php>, but that link works as intended as far as I can tell. Are you sure that it's not cached anywhere at all?

**Comment by virtadpt** [comment] 2020-11-11 23:31
I just tried that link and got a 404 error as well.
![edited](https://user-images.githubusercontent.com/639730/98876348-f27a5400-2432-11eb-8dcd-03116c05ea99.png)

**Comment by sbrl** [comment] 2020-11-12 22:15
@virtadpt Where did you find that link? I'm even more confused now. The correct URL for the downloader is:

https://starbeamrainbowlabs.com/labs/peppermint/download.php

This is the URL specified on the page here:

https://starbeamrainbowlabs.com/labs/peppermint/build/index.php?page=Main%20Page

I can't find the **incorrect** URL `https://starbeamrainbowlabs.com/peppermint/` anywhere.

**Comment by virtadpt** [comment] 2020-11-13 18:37
@sbrl That's the link that @sunjam originally posted in this ticket.  I gave it a try and got the same result.

I don't know where @sunjam got it...

**Comment by sbrl** [comment] 2020-11-20 21:18
Ah, I see. That URL is not correct, and I don't remember putting a link to it anywhere.

It reminds me of another issue I have actually, where I get requests for JS libraries on my main site with an old path, but I can't find any references that I haven't updated thereto.....

Anyway, I'm going to close this issue for now, since there doesn't seem to be any broken links that I can find.

If anyone finds a another broken link, please open a new issue with the following:

1. The broken URL itself
2. The URL of the page you found it on
3. A screenshot of where the broken link is located on the page you found it on.

**Closed** 2020-11-20 21:18 UTC
Labels: Area: Documentation, bug
